# Form implementation generated from reading ui file 'TitleWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TitleWindow(object):
    def setupUi(self, TitleWindow):
        TitleWindow.setObjectName("TitleWindow")
        TitleWindow.resize(686, 687)
        self.centralwidget = QtWidgets.QWidget(TitleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.menu_label = QtWidgets.QLabel(self.centralwidget)
        self.menu_label.setObjectName("menu_label")
        self.verticalLayout.addWidget(self.menu_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.query_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.query_menu_button.setObjectName("query_menu_button")
        self.horizontalLayout.addWidget(self.query_menu_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.update_database_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_database_menu_button.setObjectName("update_database_menu_button")
        self.horizontalLayout.addWidget(self.update_database_menu_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        TitleWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TitleWindow)
        QtCore.QMetaObject.connectSlotsByName(TitleWindow)

    def retranslateUi(self, TitleWindow):
        _translate = QtCore.QCoreApplication.translate
        TitleWindow.setWindowTitle(_translate("TitleWindow", "MainWindow"))
        self.title_label.setText(_translate("TitleWindow", "Movies Database!"))
        self.menu_label.setText(_translate("TitleWindow", "Please Select a Menu"))
        self.query_menu_button.setText(_translate("TitleWindow", "Queries"))
        self.update_database_menu_button.setText(_translate("TitleWindow", "Update Database"))
        self.exit_button.setText(_translate("TitleWindow", "Exit"))
